repository_name: scraper-backend

vpc:
  id: ${vpc_id}
  tier: "public"

iam:
  scope: "accounts"
  requires_mfa: false

microservice:
  container:
    traffics:
      - listener:
          protocol: "http"
        target:
          protocol: "http"
    ecs: {}
    group:
      name: unique
      deployment:
        min_size: 1
        desired_size: 1
        max_size: 1
        container:
          name: unique
          docker:
            registry:
              ecr:
                privacy: "private"
            repository:
              name: "scraper-backend-${branch_name}"
            image:
              tag: latest
          readonly_root_filesystem: true

      ec2:
        instance_types: ["t3.medium"]
        os: "linux"
        os_version: "2023"
        capacities:
          - type: "ON_DEMAND"
            weight: 50

bucket_env:
  file_key: "${branch_name}.env"
  force_destroy: false
  versioning: true

tags:
  "Git Microservice": "github.com/dresspeng/scraper-backend@${branch_name}"
  "Project": "scraper"
  "Service": "backend"
