organization:
  variables:
    - key: DOMAIN_NAME
      value: vistimi.com
    # - key: ECR_REGISTRY_PUBLIC_ALIAS
    #   value: h4s7f1i8
    - key: SSH_PUBLIC_KEY
      value: ${SSH_PUBLIC_KEY}
    - key: VPC_ID
      value: ${VPC_ID}
  secrets:
    - key: GH_TERRA_TOKEN
      value: ${GH_TERRA_TOKEN}
    - key: SSH_PRIVATE_KEY
      value: ${SSH_PRIVATE_KEY}

repositories:
  - accesses:
      - owner: vistimi
        name: infrastructure-live
      - owner: vistimi
        name: infrastructure-projects
      - owner: vistimi
        name: infrastructure-modules
      - owner: vistimi
        name: terraform-aws-microservice
      - owner: vistimi
        name: tryon-frontend
    variables:
      - key: CONTAINER_REGISTRY_PRIVACY
        value: private
    secrets:
  - accesses:
      - owner: vistimi
        name: infrastructure-modules
      - owner: vistimi
        name: infrastructure-live
    variables:
      # - key: CONTAINER_REGISTRY_ARGS
      #   value:
      #     '--arg repo_bin  "VARIANT=$(if [[ $ECR_PRIVACY == private ]]; then echo $ECR_REGISTRY_PRIVATE_URI; else echo $ECR_REGISTRY_PUBLIC_URI/$ECR_REGISTRY_PUBLIC_ALIAS; fi)/$(echo $REPOSITORY_NAME-$BRANCH_NAME-bin | tr A-Z a-z)"
      #     --arg repo_bin_1_4_4  "VARIANT=$(if [[ $ECR_PRIVACY == private ]]; then echo $ECR_REGISTRY_PRIVATE_URI; else echo $ECR_REGISTRY_PUBLIC_URI/$ECR_REGISTRY_PUBLIC_ALIAS; fi)/$(echo $REPOSITORY_NAME-$BRANCH_NAME-bin | tr A-Z a-z):1.4.4"'
      - key: CONTAINER_REGISTRY_JSON
        value: '[{ "path":"Dockerfile" },{ "path":"Dockerfile","args": [ "TERRAFORM_VERSION=1.4.4","TERRAGRUNT_VERSION=0.45.0"], "tags":["1.4.4"]},{ "path":"Dockerfile","args": [ "VARIANT=mcr.microsoft.com/devcontainers/base:alpine-3.16" ], "extension": "devcontainer" }]'
    secrets:
  - accesses:
      - owner: vistimi
        name: tryon-frontend
      - owner: vistimi
        name: terraform-aws-microservice
    variables:
      - key: CONTAINER_REGISTRY_JSON
        value: '[{ "path": "Dockerfile" }]'
    secrets:
  - accesses:
      - owner: vistimi
        name: terraform-aws-microservice
    variables:
      - key: CONTAINER_REGISTRY_JSON
        value: '[{ "path": "test/Dockerfile" }]'
    secrets:
