inputs:
  vpc:
    id: ${vpc_id}
    tag_tier: "public"

  traffics:
    - listener:
        protocol: "http"
      target:
        port: ${port}
        health_check_path: ${health_check_path}
      base: true
    - listener:
        protocol: "https"

  route53:
    zones:
      - name: ${zone}
    record:
      prefixes: ["www"]
      subdomain_name: ${subdomain_prefix}viton-hd

  orchestrator:
    ecs: {}
    group:
      name: one
      deployment:
        min_size: 1
        desired_size: 1
        max_size: 1
        containers:
          - name: one
            docker:
              registry:
                ecr:
                  privacy: "private"
              repository:
                name: "viton-hd-${branch_name}-rest"
                # name: "viton-hd-${branch_name}-infra-serve"
              image:
                tag: latest
                # tag: gmm
            readonly_root_filesystem: false
      ec2:
        instance_types: ["c7i.8xlarge"]
        # instance_types: ["inf1.6xlarge"]
        os: "linux"
        os_version: "2"
        capacities:
          - type: "ON_DEMAND"

  tags:
    Git Microservice: github.com/vistimi/VITON-HD@${branch_name}
    Project: tryon
    Service: backend
