name: "Terraform Format"

on:
  pull_request:

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: 'infra'
  COMPANY_REF: ${{ vars.COMPANY_REF }}
  REPO_REF: ${{ vars.REPO_REF }}
  BRANCH_REF: ${{ github.head_ref || github.ref_name }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_PROFILE_NAME: ${{ vars.AWS_PROFILE_NAME }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terragrunt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Terragrunt Format
        uses: gruntwork-io/terragrunt-action@main
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
      
      - name: Terraform Format
        uses: gruntwork-io/terragrunt-action@main
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'fmt --check --diff'